language: python

python:
  - 3.5
  - 3.6

sudo: false

cache:
  - pip

install:
  - pip install -e .[test]

script:
  - flake8 .
  - mypy --ignore-missing-imports owattr.py
  - py.test tests.py --cov=owattr --cov-report term-missing
  - rst2html.py README.rst --exit-status=2 > /dev/null
